package main

import (
	"bytes"
	"crypto/hmac"
	"crypto/sha256"
	"encoding/binary"
	"encoding/json"
	"testing"
)

// TestPythonTokenInterop verifies Go can decode tokens generated by Python's TokenManager.
// Reproduces the exact logic from nexus/cluster_protocol.py TokenManager.issue_token()
func TestPythonTokenInterop(t *testing.T) {
	secret := "test-secret"
	clusterID := "cluster-1"
	repeaterID := 312000

	// Build token payload exactly as Python does:
	// json.dumps({...}, separators=(',', ':')).encode('utf-8')
	payload := map[string]interface{}{
		"v":   1,
		"rid": repeaterID,
		"s1":  []int{8, 9},
		"s2":  []int{3120},
		"iat": 1709740800.0,
		"exp": 1709827200.0,
		"cid": clusterID,
	}
	// Python uses separators=(',', ':') which is compact JSON — same as Go's json.Marshal
	payloadBytes, err := json.Marshal(payload)
	if err != nil {
		t.Fatal(err)
	}

	// Python: hmac.new(secret.encode(), payload, hashlib.sha256).digest()
	mac := hmac.New(sha256.New, []byte(secret))
	mac.Write(payloadBytes)
	signature := mac.Sum(nil) // 32 bytes

	// Python wire format: struct.pack('!H', len(payload)) + payload + signature
	tokenBytes := make([]byte, 2+len(payloadBytes)+32)
	binary.BigEndian.PutUint16(tokenBytes[0:2], uint16(len(payloadBytes)))
	copy(tokenBytes[2:2+len(payloadBytes)], payloadBytes)
	copy(tokenBytes[2+len(payloadBytes):], signature)

	// Decode in Go
	token, err := DecodeToken(tokenBytes)
	if err != nil {
		t.Fatalf("DecodeToken: %v", err)
	}

	if token.Payload.RepeaterID != repeaterID {
		t.Errorf("rid = %d, want %d", token.Payload.RepeaterID, repeaterID)
	}
	if token.Payload.ClusterID != clusterID {
		t.Errorf("cid = %s, want %s", token.Payload.ClusterID, clusterID)
	}
	if len(token.Payload.Slot1TGs) != 2 || token.Payload.Slot1TGs[0] != 8 || token.Payload.Slot1TGs[1] != 9 {
		t.Errorf("s1 = %v, want [8,9]", token.Payload.Slot1TGs)
	}
	if !bytes.Equal(token.Signature[:], signature) {
		t.Error("signature mismatch")
	}

	// Verify token_hash matches Python: hashlib.sha256(signature).digest()[:4]
	expectedHash := sha256.Sum256(signature)
	goHash := token.TokenHash()
	if !bytes.Equal(goHash, expectedHash[:4]) {
		t.Errorf("token_hash = %x, want %x", goHash, expectedHash[:4])
	}
}

// TestPythonAuthReqFormat verifies Go's AUTH_REQ matches what Python server expects.
// Python server: data[8:12] = repeater_id, data[12:] = SHA256(passphrase)
func TestPythonAuthReqFormat(t *testing.T) {
	pkt := BuildAuthReq(312100, "mypassword")

	// Verify structure matches Python expectations
	if string(pkt[0:4]) != "NXCP" {
		t.Errorf("magic = %q", string(pkt[0:4]))
	}
	if string(pkt[4:8]) != "AUTH" {
		t.Errorf("cmd = %q", string(pkt[4:8]))
	}

	rid := binary.BigEndian.Uint32(pkt[8:12])
	if rid != 312100 {
		t.Errorf("rid = %d", rid)
	}

	// Python: expected_hash = sha256(repeater_config.passphrase.encode()).digest()
	// Then: hmac.compare_digest(passphrase_hash[:32], expected_hash)
	expectedHash := sha256.Sum256([]byte("mypassword"))
	if !bytes.Equal(pkt[12:44], expectedHash[:]) {
		t.Error("passphrase hash doesn't match Python's SHA256(passphrase)")
	}
}

// TestPythonDataFormat verifies the DATA packet format matches Python's expectations.
// Python: data[12:] = DMRD payload (everything after "DMRD" prefix)
func TestPythonDataFormat(t *testing.T) {
	tokenHash := []byte{0x01, 0x02, 0x03, 0x04}

	// Simulate a 55-byte HomeBrew DMRD packet
	dmrd := make([]byte, 55)
	copy(dmrd[0:4], "DMRD")
	dmrd[4] = 0x42 // sequence
	// src ID = 312345 (3 bytes big-endian)
	dmrd[5] = 0x04
	dmrd[6] = 0xC4
	dmrd[7] = 0x29
	// dst ID = 3120 (3 bytes)
	dmrd[8] = 0x00
	dmrd[9] = 0x0C
	dmrd[10] = 0x30

	// Build native DATA packet from DMRD payload (strip "DMRD" prefix)
	dmrdPayload := dmrd[4:] // 51 bytes
	pkt := BuildData(tokenHash, dmrdPayload)

	// Verify Python can parse this:
	// sub_cmd = data[4:8] == CMD_DATA
	if string(pkt[4:8]) != "DATA" {
		t.Error("cmd")
	}

	// token_hash = data[8:12]
	if !bytes.Equal(pkt[8:12], tokenHash) {
		t.Error("token_hash position")
	}

	// dmrd_payload = data[12:]
	extractedPayload := pkt[12:]
	if len(extractedPayload) != 51 {
		t.Errorf("payload len = %d, want 51", len(extractedPayload))
	}
	if extractedPayload[0] != 0x42 {
		t.Error("sequence byte mismatch")
	}

	// Python reconstructs: full_packet = DMRD + dmrd_payload
	// This should be >= 55 bytes (DMRD(4) + 51 = 55)
	fullPacket := append([]byte("DMRD"), extractedPayload...)
	if len(fullPacket) < 55 {
		t.Errorf("reconstructed packet len = %d, want >= 55", len(fullPacket))
	}
}

// TestPythonSubscribeFormat verifies SUBSCRIBE JSON matches Python expectations.
// Python: sub_json = json.loads(data[12:].decode('utf-8'))
//
//	sub_json.get('slot1'), sub_json.get('slot2')
func TestPythonSubscribeFormat(t *testing.T) {
	th := []byte{0x01, 0x02, 0x03, 0x04}
	slot1 := []uint32{8, 9, 3120}
	slot2 := []uint32{3100, 9998}

	pkt := BuildSubscribe(th, slot1, slot2)

	// Python: sub_json = json.loads(data[12:])
	jsonBytes := pkt[12:]
	var sub map[string]interface{}
	if err := json.Unmarshal(jsonBytes, &sub); err != nil {
		t.Fatalf("JSON: %v", err)
	}

	s1, ok := sub["slot1"].([]interface{})
	if !ok {
		t.Fatal("slot1 not array")
	}
	if len(s1) != 3 {
		t.Errorf("slot1 len = %d", len(s1))
	}
	// Python expects ints
	if int(s1[0].(float64)) != 8 {
		t.Errorf("slot1[0] = %v", s1[0])
	}

	s2, ok := sub["slot2"].([]interface{})
	if !ok {
		t.Fatal("slot2 not array")
	}
	if len(s2) != 2 {
		t.Errorf("slot2 len = %d", len(s2))
	}
}

// TestPythonPingFormat verifies PING format matches Python expectations.
// Python: token_hash = data[8:12]
func TestPythonPingFormat(t *testing.T) {
	th := []byte{0xAA, 0xBB, 0xCC, 0xDD}
	pkt := BuildPing(th)

	if string(pkt[0:4]) != "NXCP" {
		t.Error("magic")
	}
	if string(pkt[4:8]) != "PING" {
		t.Error("cmd")
	}
	if !bytes.Equal(pkt[8:12], th) {
		t.Error("token_hash at wrong offset")
	}
}
